### ISSUE TITLE
"And more..." link just opens the same page on a new tab

### ISSUE THREAD

**Issue by WhyNotHugo** [openrazer/openrazer.github.io#1]
The ["and more"](https://github.com/openrazer/openrazer.github.io/blob/525c16efb93c5b5555b2d97af5907322db162766/index.html#L95) link in the applications section of the site, just opens the same page on a new tab;

* `target="_blank"` should be ommited.
* There's no element with id `applications`, nor any anchor by that name, so it just opens the top of the page. I'm guessing you wanted to point [here](https://github.com/openrazer/openrazer#applications)?

**Comment by terricain** [comment]
@lah7 ^^

**Comment by lah7** [comment]
Thanks for flagging them up, I've made some amendments. :+1:

**Comment by WhyNotHugo** [comment]
Thanks! Happy to help!
