### ISSUE TITLE
Mention elementary OS next to Ubuntu & Linux Mint

### ISSUE THREAD

**Issue by z3ntu** [openrazer/openrazer.github.io#11]
elementary seems to be always based on Ubuntu LTS and a table is available at https://en.wikipedia.org/wiki/Elementary_OS#Summary_table . But probably the add-apt-repository thing should just work(tm)?

**Comment by lah7** [comment]
It would _just work(TM)_, but elementaryOS doesn't preinstall `software-properties-gtk` which provides the command `add-apt-repository`. I've appended instructions into Ubuntu.

**Comment by z3ntu** [comment]
Thanks :)
