### ISSUE TITLE
Fedora instructions end up escaped when pasted in `zsh` shell

### ISSUE THREAD

**Issue by razzeee** [openrazer/openrazer.github.io#26]
The code here https://github.com/openrazer/openrazer.github.io/blob/b1565ead9b736c61a71b4b4085ec4745b563eb90/index.md?plain=1#L126 seems to add an additional escaping `\` on the website, which breaks the command.

![image](https://github.com/openrazer/openrazer.github.io/assets/5943908/88e2ff7a-dc70-4cfd-a2ab-a44fe68a2373)

Wrong:
```sh
sudo dnf config-manager --add-repo https://download.opensuse.org/repositories/hardware:/razer/Fedora_$\(rpm -E %fedora)/hardware:razer.repo  
```

Correct:
```sh
sudo dnf config-manager --add-repo https://download.opensuse.org/repositories/hardware:/razer/Fedora_$(rpm -E %fedora)/hardware:razer.repo 
```

**Comment by lah7** [comment]
Not seeing that here. I can copy & paste from Firefox or Chromium into a Bash shell (or text file) without it escaping `\$`.

As a guess, the shell you're using might be doing that as a security precaution. What shell are you using?

**Comment by razzeee** [comment]
Interesting, seems to really be a zsh oddity then, I can paste fine into a text editor, but the same buffer ends up with that backslash in gnome terminal

**Comment by lah7** [comment]
For what it's worth, I checked `zsh` (empty config) on `konsole` and `gnome-terminal` on a Arch Linux VM, and don't see `\$` escaping there either. Maybe there's something in your `.zshrc`, or system-wide?

I'll close this issue since there isn't a bug with the website.
