### ISSUE TITLE
Installation instructions are lacking

### ISSUE THREAD

**Issue by Nielius** [openrazer/openrazer.github.io#7]
The instructions for installing openrazer on e.g. Arch Linux, are not complete.

The [wiki page](https://github.com/openrazer/openrazer/wiki/Installation) refers to [the download section of the main site](https://openrazer.github.io/#download), but there are almost no instructions there.

I would like to add something like the following documentation either to the wiki or to the download site (which would you prefer?):

- add your user to the `plugdev` group: `sudo usermod -a -G plugdev yourusername`
- enable the daemon: `systemctl --user enable openrazer-daemon`
- restart your pc

(I could only find these steps using the error messages.)

I think these steps were both necessary and sufficient to get the driver running.

**Comment by z3ntu** [comment]
In my opinion if you're using Arch Linux and want to use 3rd party software, you should know how to install packages from the AUR. And writing "some_command openrazer-meta" will not work as most people use different software/solutions to install software from the AUR. Read the wiki page for the AUR to find out more.

For the rest of the steps (plugdev group, etc) instructions are printed as a postinstall message with red font so you don't miss it.

Enabling the daemon is not necessary as, when you access the dbus interface (e.g. with a GUI frontend), the daemon gets automatically started, and e.g. RazerGenie automatically prompts you to enable the daemon if you haven't already.
